version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/index.html
  - source: /style.css
    destination: /var/www/html/style.css
  - source: /app.js
    destination: /var/www/html/app.js
  - source: /images/logo.jpg
    destination: /var/www/html/images/logo.jpg
